### PR TITLE
ka-GE locale

### PR DESCRIPTION
**Pull request by e404r**

### CODE REVIEW

**Comment by mohsen77sk** [comment]
Why did you use English letters in the email section?
I checked the standard keyboards for your language and this was not the case.

You can check with your mobile phone using the link below.
https://inputmodes.com/

**Comment by e404r** [comment]
@mohsen77sk E-mail in Georgian is the same as in English. Emails are not created with Georgian alphabets

**Comment by mohsen77sk** [comment]
> @mohsen77sk E-mail in Georgian is the same as in English. Emails are not created with Georgian alphabets

This is true. But we proceed according to the standard of valid keyboards. So it is better to fix this.

**Comment by e404r** [comment]
> > @mohsen77sk E-mail in Georgian is the same as in English. Emails are not created with Georgian alphabets
> 
> This is true. But we proceed according to the standard of valid keyboards. So it is better to fix this.
Of course, we will fix it

**Review by mohsen77sk — APPROVED** [review]

**Review by mohsen77sk — APPROVED** [review]

**Pull request merged**
