### PR TITLE
Swedish locale

### PR DESCRIPTION
**Pull request by fredrikthelander**
Added support for Swedish keyboard layout

### CODE REVIEW

**Comment by mohsen77sk** [comment]
Hello, @fredrikthelander 
I think, you forgot to fix the layout of [email_alphabetic] and [email_shift] and [url_alphabetic] and [url_shift].

**Comment by fredrikthelander** [comment]
Hi,

No, email and url cannot contain swedish chars.

Best regards,
Fredrik

7 apr. 2023 kl. 13:10 skrev Mohsen ***@***.***>:

﻿

Hello, @fredrikthelander<https://github.com/fredrikthelander>
I think, you forgot to fix the layout of [email_alphabetic] and [email_shift] and [url_alphabetic] and [url_shift].

**Comment by mohsen77sk** [comment]
Swedish characters such as å, ä, and ö can be used in email and URLs.

Swedish characters are usually encoded in URLs using percent-encoding or Punycode.

Given the presence of Swedish characters in email and URL layouts on standard keyboard layouts such as iPhone, Android, and Windows, having them here is preferable.

**Comment by fredrikthelander** [comment]
Sure, fixed now!

**Pull request merged**
